---

name: hello-plutarch
version: 0.0.1

dependencies:
  - base
  - bytestring
  - text
  - plutarch

library:
  source-dirs: src

executable:
  main: Main.hs
  source-dirs: exe
  dependencies: hello-plutarch
